-- 코드를 입력하세요 -- 
SELECT pro.PRODUCT_CODE, SUM(pro.PRICE * off.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT AS pro INNER JOIN OFFLINE_SALE AS off
ON pro.PRODUCT_ID = off.PRODUCT_ID
GROUP BY pro.PRODUCT_CODE
ORDER BY SUM(pro.PRICE * off.SALES_AMOUNT) DESC, pro.PRODUCT_CODE ASC;