-- 코드를 입력하세요
# SELECT *
# FROM
#     USER_INFO AS UI JOIN
#     ONLINE_SALE AS OS
# ON 
#     UI.USER_ID = OS.USER_ID
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER AS GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM
    USER_INFO AS UI JOIN
    ONLINE_SALE AS OS
ON 
    UI.USER_ID = OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC