-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, CONVERT(DATE_OF_BIRTH, CHAR(10)) AS 'DATE_OF_BIRTH'
FROM MEMBER_PROFILE
WHERE
    DATE_OF_BIRTH LIKE '%-03-%' AND 
    TLNO IS NOT NULL AND
    GENDER = 'W'
ORDER BY MEMBER_ID ASC;