-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR ,
    (MAXS.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM ECOLI_DATA AS ED
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA 
      GROUP BY YEAR
     ) AS MAXS
WHERE YEAR(DIFFERENTIATION_DATE) = MAXS.YEAR
ORDER BY YEAR, YEAR_DEV