-- 코드를 작성해주세요
SELECT SUM(gr.SCORE) AS SCORE, em.EMP_NO, em.EMP_NAME, em.POSITION, em.EMAIL
FROM 
    HR_DEPARTMENT AS de
    JOIN HR_EMPLOYEES AS em
    ON de.DEPT_ID = em.DEPT_ID
    JOIN HR_GRADE AS gr
    ON em.EMP_NO = gr.EMP_NO
GROUP BY em.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;