-- 코드를 입력하세요
SELECT 
    CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT)
    AS FILE_PATH
FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_FILE AS UGF
ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE UGF.BOARD_ID = ( SELECT BOARD_ID
        FROM USED_GOODS_BOARD
        ORDER BY VIEWS DESC
        LIMIT 1
        )
ORDER BY UGF.FILE_ID DESC;
# SELECT *
#         FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_FILE AS UGF
#         ON UGB.BOARD_ID = UGF.BOARD_ID
#         ORDER BY VIEWS DESC